version: "3.7"
services:
  #############################################################################################
  ###                               ECRC-API                                                ###
  #############################################################################################
  ecrcapi:
    build:
      context: .
      args:
        - MVN_PROFILES=ecrc-api
        - ECRC_SERVICE_NAME=ecrc-api
    environment:
      - spring_profiles_active=cloud
      - ECRC_BASEURL=${ECRC_BASEURL}
      - ECRC_PASSWORD=${ECRC_PASSWORD}
      - ECRC_USERNAME=${ECRC_USERNAME}
      - ECRC_WHITELIST=${ECRC_WHITELIST}
      - ECRC_SERVER_PORT=${ECRC_SERVER_PORT}
      - ECRC_CORS_MAPPING=${ECRC_CORS_MAPPING}
      - ECRC_CORS_ALLOWED_ORIGINS=${ECRC_CORS_ALLOWED_ORIGINS}
    ports:
      - "8086:${ECRC_SERVER_PORT}"
